(ns portfolio.romaji)

(def kanaMap {:hiragana (array-map
                          :きゃ "kya"
                          :しゃ "sya"
                          :ちゃ "tya"
                          :にゃ "nya"
                          :ひゃ "hya"
                          :みゃ "mya"
                          :りゃ "rya"
                          :ぎゃ "gya"
                          :びゃ "bya"
                          :ぴゃ "pya"
                          :きゅ "kyu"
                          :ふゅ "fyu"
                          :しゅ "syu"
                          :ちゅ "tyu"
                          :にゅ "nyu"
                          :ひゅ "hyu"
                          :みゅ "myu"
                          :りゅ "ryu"
                          :ぎゅ "gyu"
                          :びゅ "byu"
                          :ぴゅ "pyu"
                          :きょ "kyo"
                          :しょ "syo"
                          :ちょ "tyo"
                          :にょ "nyo"
                          :ひょ "hyo"
                          :みょ "myo"
                          :りょ "ryo"
                          :ぎょ "gyo"
                          :びょ "byo"
                          :ぴょ "pyo"
                          :つぁ "tsa"
                          :つぃ "tsi"
                          :つぇ "tse"
                          :つぉ "tso"
                          :ちぇ "cye"
                          :しぇ "sye"
                          :じゃ "jya"
                          :じゅ "jyu"
                          :じょ "jyo"
                          :ふぁ "fya"
                          :ふぃ "fyi"
                          :ふぇ "fye"
                          :ふぉ "fyo"
                          :うぃ "wi"
                          :ゑ "'we"
                          :うぇ "we"
                          :うぉ "'wo"
                          :ゔぁ "va"
                          :ゔぃ "vi"
                          :ゔぇ "ve"
                          :ゔぉ "vo"
                          :じぇ "jye"
                          :てぃ "thi"
                          :でぃ "dhi"
                          :でゅ "dhu"
                          :とぅ "twu"
                          :し "shi"
                          :ち "chi"
                          :つ "tsu"
                          :か "ka"
                          :さ "sa"
                          :た "ta"
                          :な "na"
                          :は "ha"
                          :ま "ma"
                          :ら "ra"
                          :き "ki"
                          :に "ni"
                          :ひ "hi"
                          :み "mi"
                          :り "ri"
                          :く "ku"
                          :す "su"
                          :ぬ "nu"
                          :ふ "fu"
                          :む "mu"
                          :る "ru"
                          :け "ke"
                          :せ "se"
                          :て "te"
                          :ね "ne"
                          :へ "he"
                          :め "me"
                          :れ "re"
                          :こ "ko"
                          :そ "so"
                          :と "to"
                          :の "no"
                          :ほ "ho"
                          :も "mo"
                          :ろ "ro"
                          :わ "wa"
                          :を "wo"
                          :が "ga"
                          :ざ "za"
                          :だ "da"
                          :ば "ba"
                          :ぱ "pa"
                          :ぎ "gi"
                          :ぢ "di"
                          :じ "ji"
                          :び "bi"
                          :ぴ "pi"
                          :ぐ "gu"
                          :ず "zu"
                          :づ "du"
                          :ぶ "bu"
                          :ぷ "pu"
                          :げ "ge"
                          :ぜ "ze"
                          :で "de"
                          :べ "be"
                          :ぺ "pe"
                          :ご "go"
                          :ぞ "zo"
                          :ど "do"
                          :ぼ "bo"
                          :ぽ "po"
                          :や "ya"
                          :ゆ "yu"
                          :よ "yo"
                          :あ "a"
                          :い "i"
                          :う "u"
                          :え "e"
                          :お "o"
                          :ん "nn")
              :katakana (array-map
                          :キャ "kya"
                          :シャ "sya"
                          :チャ "tya"
                          :ニャ "nya"
                          :ヒャ "hya"
                          :ミャ "mya"
                          :リャ "rya"
                          :ギャ "gya"
                          :ビャ "bya"
                          :ピャ "pya"
                          :キュ "kyu"
                          :フュ "fyu"
                          :シュ "syu"
                          :チュ "tyu"
                          :ニュ "nyu"
                          :ヒュ "hyu"
                          :ミュ "myu"
                          :リュ "ryu"
                          :ギュ "gyu"
                          :ビュ "byu"
                          :ピュ "pyu"
                          :キョ "kyo"
                          :ショ "syo"
                          :チョ "tyo"
                          :ニョ "nyo"
                          :ヒョ "hyo"
                          :ミョ "myo"
                          :リョ "ryo"
                          :ギョ "gyo"
                          :ビョ "byo"
                          :ピョ "pyo"
                          :ツァ "tsa"
                          :ツィ "tsi"
                          :ツェ "tse"
                          :ツォ "tso"
                          :チェ "cye"
                          :シェ "sye"
                          :ジャ "jya"
                          :ジュ "jyu"
                          :ジョ "jyo"
                          :フャ "fya"
                          :フィ "fyi"
                          :フェ "fye"
                          :フョ "fyo"
                          :ウィ "wi"
                          :ヱ "'we"
                          :ウェ "we"
                          :ウォ "'wo"
                          :ヴァ "va"
                          :ヴィ "vi"
                          :ヴェ "ve"
                          :ヴォ "vo"
                          :ジェ "jye"
                          :ティ "thi"
                          :ディ "dhi"
                          :デュ "dhu"
                          :トゥ "twu"
                          :シ "shi"
                          :チ "chi"
                          :ツ "tsu"
                          :カ "ka"
                          :サ "sa"
                          :タ "ta"
                          :ナ "na"
                          :ハ "ha"
                          :マ "ma"
                          :ラ "ra"
                          :キ "ki"
                          :ニ "ni"
                          :ヒ "hi"
                          :ミ "mi"
                          :リ "ri"
                          :ク "ku"
                          :ス "su"
                          :ヌ "nu"
                          :フ "fu"
                          :ム "mu"
                          :ル "ru"
                          :ケ "ke"
                          :セ "se"
                          :テ "te"
                          :ネ "ne"
                          :ヘ "he"
                          :メ "me"
                          :レ "re"
                          :コ "ko"
                          :ソ "so"
                          :ト "to"
                          :ノ "no"
                          :ホ "ho"
                          :モ "mo"
                          :ロ "ro"
                          :ワ "wa"
                          :ヲ "wo"
                          :ガ "ga"
                          :ザ "za"
                          :ダ "da"
                          :バ "ba"
                          :パ "pa"
                          :ギ "gi"
                          :ヂ "di"
                          :ジ "ji"
                          :ビ "bi"
                          :ピ "pi"
                          :グ "gu"
                          :ズ "zu"
                          :ヅ "du"
                          :ブ "bu"
                          :プ "pu"
                          :ゲ "ge"
                          :ゼ "ze"
                          :デ "de"
                          :ベ "be"
                          :ペ "pe"
                          :ゴ "go"
                          :ゾ "zo"
                          :ド "do"
                          :ボ "bo"
                          :ポ "po"
                          :ヤ "ya"
                          :ユ "yu"
                          :ヨ "yo"
                          :ア "a"
                          :イ "i"
                          :ウ "u"
                          :エ "e"
                          :オ "o"
                          :ン "nn")})

;; inverts key and values
(def longVowels {:a "ā"
                 :i "ī"
                 :u "ū"
                 :e "ē"
                 :o "ō"})

(defn toKana [romaji whichKana]
  (reduce (fn [result [read kana]] (clojure.string/replace result read kana))
          (clojure.string/replace (clojure.string/lower-case romaji) #"((?![aeioun])[a-z])\1{1}" #(str "っ" (nth %1 1)))
          (for [[k v] (kanaMap whichKana)] [v (name k)])))

(defn fromKana [kana]
  (clojure.string/replace (clojure.string/replace
                            (clojure.string/replace
                              (reduce (fn [result [onji read]] (clojure.string/replace result onji read))
                                      kana
                                      (apply concat (for [[k v] kanaMap] (for [[kv vv] v] [(name kv) vv]))))
                              #"([aeiou])ー"
                              #(get longVowels (keyword (nth %1 1))))
                            #"(ッ|っ)([a-z])"
                            #(str (nth %1 2) (nth %1 2)))
                          #"nn"
                          "n'"))

(defn toHiragana [romaji]
  (toKana romaji :hiragana))
(defn toKatakana [romaji]
  (toKana romaji :katakana))

(js/console.log (clj->js (toHiragana "anoiーhatoーvonosukitoottakazenatsudemosokonitsumetasawomotsuaoisora")))
(js/console.log (clj->js (toKatakana "anoiーhatoーvonosukitoottakazenatsudemosokonitsumetasawomotsuaoisora")))
(js/console.log (clj->js (toHiragana "aiuekakikukekomamimumemosashisusesorarirureronnnonanuneno")))
(js/console.log (clj->js (fromKana "りゅうがあり、あのイーハトーヴォのすきとおったなつデモつめなんんのたさをもつアオイソラ")))